# Generated by Django 6.1 on 2026-08-29 19:02

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('units_needed', models.PositiveIntegerField(default=1)),
                ('hospital_name', models.CharField(max_length=150)),
                ('hospital_location', models.CharField(max_length=150)),
                ('urgency', models.CharField(choices=[('critical', 'Critical (Within 2-4 Hours)'), ('urgent', 'Urgent (Within 24 Hours)'), ('standard', 'Standard (Scheduled)')], default='urgent', max_length=20)),
                ('when_needed', models.CharField(default='As soon as possible', max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open / Searching'), ('matched', 'Donor Matched'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_uuid', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('uap_id', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('user_type', models.CharField(choices=[('student', 'UAP Student'), ('faculty', 'UAP Faculty'), ('staff', 'UAP Staff')], default='student', max_length=20)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified UAP Member'), ('pending', 'Pending Verification'), ('unverified', 'Unverified')], default='pending', max_length=20)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('department', models.CharField(default='General', max_length=100)),
                ('batch_name', models.CharField(default='UAP', max_length=50)),
                ('city_area', models.CharField(default='Dhaka', max_length=100)),
                ('profile_visible', models.BooleanField(default=True, verbose_name='Profile visible in donor search')),
                ('allow_contact_requests', models.BooleanField(default=True, verbose_name='Allow blood-contact requests')),
                ('show_phone_publicly', models.BooleanField(default=False, verbose_name='Show phone number publicly')),
                ('last_confirmed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(default='Anonymous User', max_length=100)),
                ('reason', models.CharField(choices=[('wrong_contact', 'Wrong or Unreachable Contact'), ('wrong_blood_group', 'Incorrect Blood Group Listed'), ('fake_profile', 'Fake or Impersonated Profile'), ('no_longer_donor', 'No Longer Available / Retired Donor'), ('harassment', 'Inappropriate Behavior or Harassment'), ('other', 'Other Reason')], max_length=30)),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DonationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField(default=datetime.date.today)),
                ('location', models.CharField(default='UAP Blood Bank Center', max_length=150)),
                ('verification_status', models.CharField(default='verified', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_records', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=100)),
                ('requester_phone', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bloodrequest')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to='core.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_requests', to='core.userprofile'),
        ),
    ]
