# Generated by Django 6.1 on 2026-08-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='show_phone_publicly',
            field=models.BooleanField(default=True, verbose_name='Show phone number publicly'),
        ),
    ]
