# Generated by Django 6.1 on 2026-08-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_show_phone_publicly'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='biological_sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10, verbose_name='Biological sex for donor eligibility *'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blood_group_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth *'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='donation_history_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uap_id_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='verification_status',
            field=models.CharField(choices=[('verified', 'Verified UAP Member'), ('pending', 'Pending Verification'), ('needs_correction', 'Needs Correction'), ('rejected', 'Verification Rejected'), ('unverified', 'Unverified')], default='pending', max_length=20),
        ),
    ]
